### ISSUE TITLE
Generate ...OfScalar classes

### ISSUE THREAD

**Issue by rocket-3** [victornoel/eo-envelopes#16]
1. There is an another important technique of using envelopes based on Scalar<TargetType> described in [Decorating Envelopes video](https://www.youtube.com/watch?v=Wcy53ZSF78o) by @yegor256
1. However, in reference library [Cactoos](https://github.com/yegor256/cactoos) the technique desribed above is made possible with combination of **...Envelope** + **...OfScalar** classes (which seems to have been taken as a more mature approach)

Based on this I suggest implement of generating ...OfScalar classes too as a logical continuation of the current path to reduce the time cost of applying the techniques of Elegant Objects

**Comment by victornoel** [comment]
@rocket-3 hi, you perfectly understood the spirit of how things are done in cactoos indeed!

If I understand correctly, you are asking that for an interface name `AnInterface`, we generate a class `AnInterfaceOfScalar` that implements `AnInterface` with a constructor taking a `Scalar<AnInterface>` and delegating all methods of the interface by calling the wrapped scalar `value()` method and then the delegated method.

Unfortunately, I see two reasons not to implement this here:
- it would be best to keep eo-envelopes independent of cactoos
- I personally believe that a `Scalar` based implementation of a any interface can vary depending on the actual expected behaviour of that interface and thus it would encourage potentially bad design if we automate this kind of things :)
